[package]
name = "vtd-libum-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
vtd-libum = { version = "*", path = "../vtd-libum" }

bitflags = "2.9.1"
env_logger = "0.11.8"
log = "0.4.27"

[build-dependencies]
cbindgen = "0.29.0"
